apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  RABBITMQ_HOST: 172.17.0.1
  RABBITMQ_PORT: "5672"
  RABBITMQ_HTTP_URL: http://172.17.0.1:15672
  RABBITMQ_QUEUE: task-queue
  METRICS_PORT: "8001"
